# Generated by Django 3.2.6 on 2021-10-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='strength',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
