# Generated by Django 3.2.6 on 2021-10-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_auto_20211023_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
